/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ConquerERC20__factory } from "./ConquerERC20__factory";
export { ConquerNFT__factory } from "./ConquerNFT__factory";
